### PR TITLE
Resurrect shrinking and improve it

### LINKED ISSUE #12: Shrinking is not as good as we'd have hoped
We've implemented the shrinking from V1 on plans, but when I tried to enable some shrinking tests we find that most of the shrinking still doesn't work as well as we'd have hoped. This needs investigating. C.f. comments like this in `Constrained.Tests`:
```haskell
    -- TODO: figure out why this doesn't shrink
    testSpecNoShrink "reifyYucky" reifyYucky
```

### PR DESCRIPTION
**Pull request by MaximilianAlgehed**
Take the old approach to shrinking from V1 and adapt to V2. Closes #12

### CODE REVIEW

File: src/Constrained/Base.hs [hunk 1]
```diff
@@ -488,6 +488,9 @@ class
   -- | Shrink an `a` with the aide of a `TypeSpec`
   shrinkWithTypeSpec :: TypeSpec a -> a -> [a]
 
+  -- | Try to make an `a` conform to `TypeSpec` with minimal changes
+  fixupWithTypeSpec :: TypeSpec a -> a -> Maybe a
```
Comment (Soupstraw) [inline src/Constrained/Base.hs]: Can you explain in the comment what the difference between returning a `Nothing` and `Just x` is?

**Review by Soupstraw — APPROVED** [review]
LGTM
